<?php

return [
    'whatsapp_phone' => env('LANDING_WHATSAPP_PHONE'),

    'whatsapp_default_message' => env(
        'LANDING_WHATSAPP_DEFAULT_MESSAGE',
        'সালাম, আমি WooEasyLife সম্পর্কে জানতে চাই।',
    ),

    'helpline_phone' => env('LANDING_HELPLINE_PHONE', env('LANDING_WHATSAPP_PHONE')),

    'location' => 'ঢাকা, বাংলাদেশ',

    'footer_tagline' => 'বাংলাদেশের WooCommerce মার্চেন্টদের জন্য অল-ইন-ওয়ান অটোমেশন প্ল্যাটফর্ম — আপনার ডাটা, আপনার নিয়ন্ত্রণ।',

    'footer_tagline_en' => "Bangladesh's trusted WooCommerce automation platform. Fraud check, courier sync, AI orders & multi-store management.",

    'trust_badges' => [
        ['icon' => 'check', 'label' => '৪০+ প্রিমিয়াম ফিচার'],
        ['icon' => 'clock', 'label' => '২৪/৭ মনিটরিং'],
        ['icon' => 'lock', 'label' => 'সিকিউর কানেকশন'],
    ],

    'feature_highlight_order' => [
        'ai_text_order_create',
        'ai_image_to_order_create',
        'common_dashboard',
        'multistore_order_notifications',
        'fraud_customer_checker',
        'customer_call_identifier',
        'three_courier_partner_integration',
        'courier_entry_automation',
        'ai_driven_customer_scoring',
        'ai_incomplete_address_autocomplete',
        'cross_store_order_detection',
        'centralized_notifications',
        'duplicate_order_validation',
        'customer_sms_for_order',
        'courier_auto_status_sync',
        'admin_employee_manage',
        'call_history_with_duration',
    ],

    'hero' => [
        'badge' => 'বাংলাদেশের WooCommerce মার্চেন্টদের জন্য',
        'headline' => 'ওয়েবসাইটের অর্ডার, ফ্রড, কুরিয়ার',
        'headline_accent' => '— সব এক জায়গায়। সময় বাঁচান, লাভ বাড়ান।',
        'subheadline' => 'ফ্রড চেক, কুরিয়ার অটোমেশন, কল হিস্ট্রি ও স্টাফ ট্র্যাকিং, মিসিং অর্ডার রিকভারি — একাধিক ওয়েবসাইট ফোন থেকে ম্যানেজ করুন।',
    ],

    'hero_bullets' => [
        'মাসে হাজার হাজার টাকা return loss কমান — order confirm করার আগেই fraud check',
        'দিনে ৩+ ঘণ্টা বাঁচান — কুরিয়ার, এসএমএস ও অর্ডার অটোমেশন',
        'কল হিস্ট্রি (অ্যাপে ডিউরেশন), স্টাফ অ্যাসাইন — ক্যানসেল হলে কারণ বোঝা যায়',
        'একাধিক ওয়েবসাইট এক ড্যাশবোর্ড ও মোবাইল অ্যাপে — সেন্ট্রাল ম্যানেজমেন্ট',
    ],

    'roi_scenarios' => [
        [
            'icon' => '💸',
            'title' => 'Return loss কমান',
            'calculation' => 'প্রতি return ≈ ১৫০–৩০০ টাকা · দিনে ১০টা fake order = মাসে ৪৫,০০০+ টাকা loss',
            'benefit' => 'Fraud check দিয়ে অর্ধেক কমালেই plan-এর চেয়ে বেশি save',
            'accent' => 'rose',
        ],
        [
            'icon' => '⏱️',
            'title' => 'কুরিয়ার সময় বাঁচান',
            'calculation' => '১ অর্ডারে ৪ মিনিট × ৫০ অর্ডার = ২০০ মিনিট/দিন (৩+ ঘণ্টা)',
            'benefit' => 'অটো কুরিয়ার এন্ট্রি ও স্ট্যাটাস সিঙ্ক — স্টাফ খরচ কমে',
            'accent' => 'amber',
        ],
        [
            'icon' => '📱',
            'title' => 'মিসিং অর্ডার ফিরান',
            'calculation' => 'FB/হোয়াটসঅ্যাপে ৫ অর্ডার মিস = গড় ৫০০ টাকা × ৫ = ২,৫০০/দিন',
            'benefit' => 'মিসিং অর্ডার খুঁজে ওয়ান ক্লিকে তৈরি — হারানো বিক্রি ফিরে আসে',
            'accent' => 'sky',
        ],
        [
            'icon' => '📦',
            'title' => 'প্যাকিং দ্রুত করুন',
            'calculation' => 'হাতে লেবেল ২ মিনিট × ৫০ পার্সেল = ১০০ মিনিট/দিন',
            'benefit' => 'POS স্টিকার প্রিন্ট — সেকেন্ডে পার্সেল লেবেল, ভুল কমে',
            'accent' => 'violet',
        ],
    ],

    'how_it_works' => [
        [
            'step' => '০১',
            'title' => 'প্ল্যান বেছে নিন',
            'description' => 'প্রাইসিং পেজ থেকে প্ল্যান সিলেক্ট করুন বা হোয়াটসঅ্যাপে যোগাযোগ করুন। ১৪ দিন ফ্রি ট্রায়াল উপলব্ধ।',
        ],
        [
            'step' => '০২',
            'title' => 'ওয়েবসাইটে প্লাগইন কানেক্ট',
            'description' => 'WooCommerce ওয়েবসাইটে WooEasyLife প্লাগইন ইনস্টল করে লাইসেন্স অ্যাক্টিভ করুন।',
        ],
        [
            'step' => '০৩',
            'title' => 'অটোমেশন চালু করুন',
            'description' => 'ফ্রড চেক, কুরিয়ার, এসএমএস ও মিসিং অর্ডার টুল চালু করুন — লাভ বাড়তে শুরু করুন।',
        ],
        [
            'step' => '০৪',
            'title' => 'অ্যাপে সব ওয়েবসাইট',
            'description' => 'মোবাইল অ্যাপে একাধিক ওয়েবসাইট কানেক্ট করুন — অর্ডার, কল ও নোটিফিকেশন ফোনে পান।',
        ],
    ],

    'app_showcase' => [
        'headline' => 'মোবাইল অ্যাপে সব ওয়েবসাইট কন্ট্রোল করুন',
        'subheadline' => 'Dashboard, Orders, Missing Orders — সব badge সহ এক sidebar-এ। Push notification on রাখলেই নতুন order alert ফোনে।',
        'screenshot' => '/images/woo-easy-life/app-left-sidebar.png',
        'screenshot_alt' => 'WooEasyLife মোবাইল অ্যাপ — sidebar, dashboard, orders ও missing orders',
        'benefits' => [
            'Common Dashboard — New ও Courier order count এক নজরে',
            'Missing Orders badge — FB/WhatsApp order miss হলে দ্রুত খুঁজুন',
            'Push notification — নতুন order alert সরাসরি ফোনে',
            'Company Employee ও multi-website — সব account এক app-এ',
        ],
    ],

    'fraud_benefit_cards' => [
        'headline' => 'Order confirm করার আগেই customer কেমন — জেনে নিন',
        'subtitle' => 'Fake order confirm korle return khoroch — courier data দিয়ে আগেই decide করুন',
        'cards' => [
            [
                'icon' => '📊',
                'title' => 'Success rate দেখুন',
                'description' => 'Steadfast, Pathao, RedX — কত delivery, কত return। এক নজরে customer-এর courier profile।',
            ],
            [
                'icon' => '✅',
                'title' => 'Delivery history',
                'description' => 'Customer আগে কতবার order করেছে, কতবার successful delivery — সব record একসাথে।',
            ],
            [
                'icon' => '🛡️',
                'title' => 'Fake order ধরুন',
                'description' => 'Fraud note, low success rate, risky pattern — order confirm করার আগেই red flag দেখুন।',
            ],
            [
                'icon' => '📱',
                'title' => 'Free check এখনই',
                'description' => 'Registration ছাড়াই number দিন — landing page-এ daily free search, instant result।',
                'cta' => '#fraud-check',
                'cta_label' => 'Check করুন',
            ],
        ],
    ],

    'feature_showcases' => [
        [
            'id' => 'fraud',
            'badge' => 'Fraud Protection',
            'headline' => 'Order confirm করার আগেই customer কেমন — জেনে নিন',
            'teaser' => 'Courier data দিয়ে fraud check — return loss কমান',
            'pain' => 'Fake order confirm করলে return খরচ, packaging loss আর courier charge চলে যায়। অনেক merchant মাসে লাখ টাকারও বেশি loss করে।',
            'solution' => 'Courier delivery history দিয়ে fraud check, duplicate block, checkout OTP — order confirm করার আগেই decide করুন।',
            'benefit' => 'Return কমে, confirmed delivery বাড়ে — মাসে হাজার হাজার টাকা save, cash flow ভালো থাকে।',
            'highlights' => [
                'Landing page-এ free fraud check — registration ছাড়াই',
                'Steadfast fraud note + courier success rate',
                'Duplicate order আর checkout protection',
            ],
            'read_more' => [
                [
                    'title' => 'Fraud check কেন দরকার?',
                    'body' => 'Bangladesh-এ COD business-এ fake/risky order বড় সমস্যা। একবার parcel চলে গেলে return charge, packaging আর time — সব loss। WooEasyLife-এ order confirm করার আগেই courier data দেখে decide নিন।',
                ],
                [
                    'title' => 'কীভাবে কাজ করে?',
                    'body' => 'Customer-এর number দিয়ে Steadfast, Pathao, RedX-এর delivery history, success rate আর fraud note একসাথে দেখুন। Risk বেশি হলে order confirm না cancel — আপনার control-এ।',
                ],
            ],
            'accent' => 'emerald',
            'feature_keys' => ['fraud_customer_checker', 'duplicate_order_validation', 'customer_delivery_history', 'checkout_otp_validation'],
        ],
        [
            'id' => 'team',
            'badge' => 'কল হিস্ট্রি ও অর্ডার অ্যাকাউন্টেবিলিটি',
            'headline' => 'ক্যানসেল হলে জানুন কেন — কে কল করেছিল, কতক্ষণ, কে অর্ডার প্রসেস করেছিল',
            'teaser' => 'অ্যাপ + প্লাগইন — কল, স্টাফ ও ক্যানসেল ডাটা এক জায়গায়',
            'pain' => 'অর্ডার ক্যানসেল হলে বোঝা যায় না — স্টাফ ঠিকমতো কল করেছিল কিনা, কতক্ষণ কথা হয়েছিল, কে অর্ডার হ্যান্ডেল করেছিল। দোষ কার, সমস্যা কোথায় — অনুমানেই চলতে হয়।',
            'solution' => 'প্লাগইন ও অ্যাপে কল হিস্ট্রি দেখুন; অ্যাপ দিয়ে কল করলে প্রতিটি কলের ডিউরেশন সেভ হয়। অর্ডারে স্টাফ অ্যাসাইন করুন, সোর্স ও কাস্টমার কল শনাক্ত করুন — ক্যানসেল অর্ডারে সব ডাটা একসাথে।',
            'benefit' => 'ক্যানসেলের কারণ বোঝা যায়, স্টাফ ট্রেনিং ও দায়িত্ব স্পষ্ট হয়, ফেইক কাস্টমার vs দুর্বল ফলো-আপ আলাদা করা যায় — অনাকাঙ্ক্ষিত লস কমে।',
            'highlights' => [
                'অ্যাপ থেকে কল — প্রতিটি কলের সময়কাল (ডিউরেশন) রেকর্ড',
                'অর্ডারে এমপ্লয়ি অ্যাসাইন — কে প্রসেস করছে ট্র্যাক',
                'ক্যানসেল অর্ডারে কল + স্টাফ + সোর্স দেখে কারণ বিশ্লেষণ',
            ],
            'scenario' => [
                'title' => 'উদাহরণ: ক্যানসেল অর্ডার #৪৮২১',
                'steps' => [
                    'কাস্টমার অর্ডার করল — স্টাফ «রাহিম» অ্যাসাইন',
                    'রাহিম অ্যাপ থেকে ৪ মিনিট ৩২ সেকেন্ড কল করল',
                    'পরে অর্ডার ক্যানসেল — কল হিস্ট্রি ও নোট দেখে বোঝা গেল কাস্টমার COD নিতে অনিচ্ছুক',
                    'সিদ্ধান্ত: পরবর্তীতে এই নম্বরে ফোন-কনফার্ম বাধ্যতামূলক',
                ],
            ],
            'read_more' => [
                [
                    'title' => 'কল হিস্ট্রি — প্লাগইন vs অ্যাপ',
                    'body' => 'প্লাগইন ও ড্যাশবোর্ডে কল হিস্ট্রি দেখতে পারবেন — কোন নম্বরে কখন কল হয়েছিল। মোবাইল অ্যাপ দিয়ে কল করলে অতিরিক্ত সুবিধা: প্রতিটি কলের ডিউরেশন (কত মিনিট/সেকেন্ড) অটো সেভ হয়। ফলে বোঝা যায় কোন স্টাফ কতক্ষণ কাস্টমারের সাথে কথা বলছে — পারফরম্যান্স মাপা ও ট্রেনিং দেওয়া সহজ হয়।',
                ],
                [
                    'title' => 'এমপ্লয়ি অ্যাসাইন ও অর্ডার ট্র্যাকিং',
                    'body' => 'প্রতিটি অর্ডারে স্টাফ অ্যাসাইন করুন। কোন এমপ্লয়ি কোন অর্ডার প্রসেস করছে, কোন সোর্স থেকে (Facebook, হোয়াটসঅ্যাপ, ওয়েবসাইট) অর্ডার এসেছে — সব ট্র্যাক হয়। মালিক হিসেবে দেখতে পারবেন কে কত অর্ডার হ্যান্ডেল করছে, দায়িত্ব কোথায় ঘাটতি।',
                ],
                [
                    'title' => 'ক্যানসেল হলে ডাটা কীভাবে সাহায্য করে?',
                    'body' => 'অর্ডার ক্যানসেল হলে শুধু «ক্যানসেল» দেখে থেমে যাওয়ার দিন শেষ। WooEasyLife-এ ক্যানসেল অর্ডারে কল হিস্ট্রি (ডিউরেশন সহ), অ্যাসাইন করা স্টাফ, অর্ডার সোর্স ও কাস্টমার প্রোফাইল একসাথে দেখুন। ফেইক/অযোগ্য কাস্টমার পATTERN, স্টাফের দুর্বল ফলো-আপ, বা প্রোডাক্ট/দাম সমস্যা — কোনটা বেশি হচ্ছে তা বোঝা যায়। পরবর্তী সিদ্ধান্ত ডাটা দিয়ে নিন, অনুমানে নয়।',
                ],
                [
                    'title' => 'টিম ম্যানেজমেন্ট',
                    'body' => 'রোল ভিত্তিক অ্যাক্সেস, ওয়েবসাইট অনুযায়ী স্টাফ অ্যাসাইন, পোর্টাল লগইন — ছোট টিমও প্রফেশনালভাবে চলে। ইনকামিং কলে কাস্টমার শনাক্ত হয়, স্টাফ দ্রুত অর্ডার হিস্ট্রি দেখে রেসপন্স দিতে পারে।',
                ],
            ],
            'accent' => 'violet',
            'feature_keys' => ['admin_employee_manage', 'call_history_with_duration', 'order_source_identifier', 'customer_call_identifier'],
        ],
        [
            'id' => 'courier',
            'badge' => 'কুরিয়ার অটোমেশন',
            'headline' => 'কুরিয়ার প্যানেলে বসে সময় নষ্ট করবেন না',
            'teaser' => 'Steadfast, Pathao, RedX — অর্ডার কনফার্ম হলেই অটো এন্ট্রি',
            'pain' => 'প্রতি অর্ডারে কুরিয়ার প্যানেলে ম্যানুয়াল এন্ট্রি — দিনে ৩+ ঘণ্টা চলে যায়। ভুল এন্ট্রি হলে ভুল ডেলিভারি ও কাস্টমার অসন্তোষ।',
            'solution' => 'Steadfast, Pathao, RedX — অর্ডার কনফার্ম হলেই অটো এন্ট্রি, স্ট্যাটাস সিঙ্ক ও কাস্টমার এসএমএস। এক ড্যাশবোর্ড থেকে সব কুরিয়ার।',
            'benefit' => 'সময় বাঁচে, ভুল কমে, স্টাফ অন্য কাজে লাগে — দিনে ৫০+ অর্ডারও স্মুথলি চলে।',
            'highlights' => [
                '৩+ কুরিয়ার এক প্ল্যাটফর্ম',
                'অটো কুরিয়ার এন্ট্রি ও স্ট্যাটাস সিঙ্ক',
                'অর্ডার আপডেট কাস্টমারকে এসএমএস',
            ],
            'read_more' => [
                [
                    'title' => 'ম্যানুয়াল vs অটো',
                    'body' => 'প্রতি অর্ডারে কুরিয়ার ওয়েবসাইটে লগইন, কপি-পেস্ট, কনসাইনমেন্ট ID — এগুলো দিনে ঘণ্টা নষ্ট করে। WooEasyLife অর্ডার স্ট্যাটাস বদলালেই কুরিয়ারে এন্ট্রি ও আপডেট হয়।',
                ],
                [
                    'title' => 'এসএমএস ও ট্র্যাকিং',
                    'body' => 'কাস্টমারকে অর্ডার ও ডেলিভারি আপডেট এসএমএসে যায় — «কোথায় আমার পার্সেল?» কল কমে।',
                ],
            ],
            'accent' => 'amber',
            'feature_keys' => ['three_courier_partner_integration', 'courier_entry_automation', 'courier_auto_status_sync', 'customer_sms_for_order'],
        ],
        [
            'id' => 'missing',
            'badge' => 'মিসিং অর্ডার রিকভারি',
            'headline' => 'Facebook/হোয়াটসঅ্যাপের অর্ডার হারিয়ে যাচ্ছে?',
            'teaser' => 'মিসিং অর্ডার খুঁজে ওয়ান ক্লিকে WordPress-এ তৈরি করুন',
            'pain' => 'মেসেজে অর্ডার আসে কিন্তু WordPress-এ থাকে না — বিক্রি হারায়। স্টাফ ভুলে এন্ট্রি না করলে বা সিস্টেম গ্লিচ হলে টাকা চলে যায়।',
            'solution' => 'মিসিং অর্ডার খুঁজে ওয়ান ক্লিকে তৈরি করুন, অর্ডার ক্লোন ও কুইক অ্যাকশন দিয়ে দ্রুত হ্যান্ডেল করুন।',
            'benefit' => 'হারানো অর্ডার ফিরে আসে — দিনে হাজার টাকা বিক্রি রিকভার, রেভিনিউ লিক বন্ধ হয়।',
            'highlights' => [
                'FB/হোয়াটসঅ্যাপ অর্ডার vs WordPress মিলিয়ে খুঁজে বের',
                'ওয়ান ক্লিকে মিসিং অর্ডার তৈরি',
                'অর্ডার ক্লোন — দ্রুত পুনরায় এন্ট্রি',
            ],
            'read_more' => [
                [
                    'title' => 'কেন মিসিং অর্ডার হয়?',
                    'body' => 'বাংলাদেশে অনেক বিক্রি Facebook বা হোয়াটসঅ্যাপ DM-এ আসে, পরে ম্যানুয়ালি WooCommerce-এ এন্ট্রি হয়। ব্যস্ততায় বা স্টাফ পরিবর্তনে অর্ডার মিস হয়। মিসিং অর্ডার ফিচার দিয়ে গ্যাপ খুঁজে পূরণ করুন।',
                ],
            ],
            'accent' => 'sky',
            'feature_keys' => ['missing_orders', 'missing_order_one_click_create', 'order_cloning', 'quick_action_tool'],
        ],
        [
            'id' => 'print',
            'badge' => 'প্যাকিং ও প্রিন্ট',
            'headline' => 'পার্সেল স্টিকার — সেকেন্ডে, ভুল ছাড়া',
            'teaser' => 'POS স্টিকার ও ইনভয়েস — প্যাকিং টিমের জন্য প্রস্তুত',
            'pain' => 'হাতে নাম-ঠিকানা লিখতে সময় যায়, ভুল হলে ভুল ডেলিভারি ও রিটার্ন। বড় অর্ডার ভলিউমে প্যাকিং বটleneck হয়।',
            'solution' => 'POS স্টিকার প্রিন্ট ও ওয়ান ক্লিক ইনভয়েস, ইনলাইন শিপিং পরিবর্তন ও অর্ডার নোট — প্যাকিং লাইন দ্রুত চলে।',
            'benefit' => 'প্যাকিং ২x দ্রুত, ভুল কমে, অপারেশন স্মুথ — দিনে আরও অর্ডার প্রসেস করুন।',
            'highlights' => [
                'POS স্টিকার — নাম, ঠিকানা, ফোন প্রিন্ট',
                'ওয়ান ক্লিক ইনভয়েস',
                'প্যাকিং টিমের জন্য স্ট্যান্ডার্ড ফরম্যাট',
            ],
            'read_more' => [
                [
                    'title' => 'প্যাকিং স্পিড',
                    'body' => 'হাতে লেখা লেবেলে ভুল ঠিকানা = রিটার্ন খরচ। POS স্টিকারে WooCommerce ডাটা সরাসরি প্রিন্ট — সেকেন্ডে লেবেল, কম ভুল।',
                ],
            ],
            'accent' => 'violet',
            'feature_keys' => ['pos_sticker_print', 'invoice_print', 'inline_shipping_change', 'order_note_management'],
        ],
        [
            'id' => 'ai',
            'badge' => 'এআই ইন্টিগ্রেটেড',
            'headline' => 'মেসেজ থেকে অর্ডার — হাতে টাইপের দিন শেষ',
            'teaser' => 'টেক্সট বা ছবি থেকে এআই অর্ডার — ৩০ সেকেন্ডে',
            'pain' => 'কাস্টমারের মেসেজ/ছবি দেখে হাতে অর্ডার টাইপ — ৫–১০ মিনিট প্রতি অর্ডার। ভুল ঠিকানা, ভুল প্রোডাক্ট — সাধারণ ভুল।',
            'solution' => 'এআই দিয়ে টেক্সট/ছবি থেকে অর্ডার, ঠিকানা অটো-কমপ্লিট, কাস্টমার স্কোরিং — দ্রুত ও কম ভুল।',
            'benefit' => '৩০ সেকেন্ডে অর্ডার — দিনে ঘণ্টার পর ঘণ্টা সময় বাঁচে, আরও অর্ডার হ্যান্ডেল করুন।',
            'highlights' => [
                'মেসেজ পেস্ট — এআই অর্ডার তৈরি',
                'ছবি/স্ক্রিনশট থেকে অর্ডার',
                'অসম্পূর্ণ ঠিকানা অটো পূরণ',
            ],
            'read_more' => [
                [
                    'title' => 'এআই অর্ডার ক্রিয়েশন',
                    'body' => 'কাস্টমার «২টা শার্ট, XL, ঢাকা» লিখল — এআই পarse করে অর্ডার ফিল্ড পূরণ করে। স্ক্রিনশট থেকেও অর্ডার বানানো যায়।',
                ],
                [
                    'title' => 'কাস্টমার স্কোরিং',
                    'body' => 'এআই + কুরিয়ার ডাটা মিলিয়ে কাস্টমার রিস্ক স্কোর — কাকে ফোন-কনফার্ম করবেন সিদ্ধান্ত সহজ।',
                ],
            ],
            'accent' => 'fuchsia',
            'feature_keys' => ['ai_text_order_create', 'ai_image_to_order_create', 'ai_incomplete_address_autocomplete', 'ai_driven_customer_scoring'],
        ],
        [
            'id' => 'websites',
            'badge' => 'একাধিক ওয়েবসাইট',
            'headline' => '২–৩টা ওয়েবসাইট — সব আপনার আঙুলের ডগায়',
            'teaser' => 'সব WooCommerce ওয়েবসাইট এক ড্যাশবোর্ড ও অ্যাপে',
            'pain' => 'প্রতিটি ওয়েবসাইটের admin আলাদা খুলে ঘোরা — সময় নষ্ট, অর্ডার মিস, স্টাফ বিভ্রান্ত।',
            'solution' => 'সব ওয়েবসাইট এক ড্যাশবোর্ড ও মোবাইল অ্যাপে — সেন্ট্রাল নোটিফিকেশন, QR কানেক্ট।',
            'benefit' => 'সাইট বদলাতে ৩০–৪৫ মিনিট/দিন বাঁচে — সব কিছু হাতের মুঠোয়, স্কেল করা সহজ।',
            'highlights' => [
                '২–৩ বা আনলিমিটেড ওয়েবসাইট (প্ল্যান অনুযায়ী)',
                'সব সাইটের অর্ডার এক অ্যাপে',
                'ওয়ান ক্লিক QR কানেক্ট',
            ],
            'read_more' => [
                [
                    'title' => 'মাল্টি-ওয়েবসাইট মার্চেন্ট',
                    'body' => 'একাধিক নিশ বা ব্র্যান্ড চালান? প্রতিটি WooCommerce আলাদা লগইন — nightmare। WooEasyLife সব সাইট এক জায়গায়: অর্ডার, কুরিয়ার, ফ্রড, স্টাফ — এক ড্যাশবোর্ড।',
                ],
            ],
            'accent' => 'cyan',
            'feature_keys' => ['common_dashboard', 'multistore_order_notifications', 'one_click_app_connect', 'centralized_notifications'],
        ],
    ],

    'value_pillars' => [
        [
            'id' => 'ai',
            'badge' => 'এআই ইন্টিগ্রেটেড',
            'headline' => 'এআই দিয়ে অর্ডার — হাতে টাইপ করার দিন শেষ',
            'subheadline' => 'কাস্টমারের মেসেজ, ছবি বা অসম্পূর্ণ ঠিকানা থেকে স্মার্ট অর্ডার তৈরি। সময় বাঁচান, ভুল কমান।',
            'accent' => 'fuchsia',
            'feature_keys' => [
                'ai_text_order_create',
                'ai_image_to_order_create',
                'ai_incomplete_address_autocomplete',
                'ai_driven_customer_scoring',
                'customer_behavior_track',
            ],
        ],
        [
            'id' => 'multistore',
            'badge' => 'একাধিক ওয়েবসাইট',
            'headline' => 'একাধিক ওয়েবসাইট — সব আপনার আঙুলের ডগায়',
            'subheadline' => '২–৩টা বা আনলিমিটেড ওয়েবসাইট এক অ্যাপ ও এক ড্যাশবোর্ডে। সাইট বদলাতে সময় নষ্ট হবে না।',
            'accent' => 'sky',
            'feature_keys' => [
                'common_dashboard',
                'multistore_order_notifications',
                'one_click_app_connect',
                'cross_store_order_detection',
                'centralized_notifications',
                'customer_call_identifier',
            ],
        ],
        [
            'id' => 'team',
            'badge' => 'স্মার্ট টিম ম্যানেজমেন্ট',
            'headline' => 'টিম পারফরম্যান্স ট্র্যাক করুন — সবাই এক লাইনে',
            'subheadline' => 'রোল ভিত্তিক অ্যাক্সেস, ওয়েবসাইট অনুযায়ী টিম অ্যাসাইন ও কল/অর্ডার পারফরম্যান্স দেখুন।',
            'accent' => 'violet',
            'feature_keys' => [
                'admin_employee_manage',
                'call_history_with_duration',
                'customer_call_identifier',
                'order_source_identifier',
            ],
        ],
        [
            'id' => 'protection',
            'badge' => 'Fraud Protection',
            'headline' => 'Order confirm করার আগেই customer কেমন — জেনে নিন',
            'subheadline' => 'Courier data দিয়ে fraud check, duplicate block আর checkout protection — return কমান, profit বাড়ান।',
            'accent' => 'emerald',
            'feature_keys' => [
                'fraud_customer_checker',
                'duplicate_order_validation',
                'customer_delivery_history',
                'repeat_customer_identifier',
                'checkout_otp_validation',
                'bd_ip_restriction',
            ],
        ],
        [
            'id' => 'automation',
            'badge' => 'ফুল অটোমেশন',
            'headline' => 'কুরিয়ার, এসএমএস, ইনভয়েস — সব অটো',
            'subheadline' => 'Steadfast, Pathao, RedX এক ক্লিকে। অর্ডার কনফার্ম হলেই কুরিয়ার এন্ট্রি, এসএমএস ও স্ট্যাটাস সিঙ্ক।',
            'accent' => 'amber',
            'feature_keys' => [
                'three_courier_partner_integration',
                'courier_entry_automation',
                'courier_auto_status_sync',
                'customer_sms_for_order',
                'invoice_print',
                'missing_order_one_click_create',
            ],
        ],
    ],

    'feature_icons' => [
        'fraud_customer_checker' => 'shield',
        'three_courier_partner_integration' => 'truck',
        'courier_entry_automation' => 'truck',
        'courier_auto_status_sync' => 'truck',
        'courier_webhook_integrations' => 'truck',
        'customer_sms_for_order' => 'message',
        'bulk_sms' => 'message',
        'duplicate_order_validation' => 'clipboard',
        'checkout_form_validation' => 'clipboard',
        'ai_text_order_create' => 'spark',
        'ai_image_to_order_create' => 'spark',
        'invoice_print' => 'print',
        'one_click_app_connect' => 'phone',
        'multistore_order_notifications' => 'phone',
        'customer_call_identifier' => 'phone',
        'common_dashboard' => 'dashboard',
        'admin_employee_manage' => 'users',
        'call_history_with_duration' => 'phone',
        'order_source_identifier' => 'clipboard',
    ],

    'groups' => [
        'Courier' => 'কুরিয়ার অটোমেশন',
        'Customer' => 'কাস্টমার ইন্টেলিজেন্স',
        'SMS' => 'এসএমএস নোটিফিকেশন',
        'AI Featuree' => 'এআই ফিচার',
        'Checkout' => 'চেকআউট সুরক্ষা',
        'Orders' => 'অর্ডার ম্যানেজমেন্ট',
        'Block & restrict' => 'ফ্রড ও ব্লক',
        'Tools' => 'বিজনেস টুলস',
        'Print' => 'প্রিন্ট ও ইনভয়েস',
        'App' => 'মোবাইল অ্যাপ',
    ],

    'labels' => [
        'fraud_customer_checker' => 'ফ্রড কাস্টমার চেকার',
        'three_courier_partner_integration' => '৩টি কুরিয়ার পার্টনার ইন্টিগ্রেশন',
        'courier_entry_automation' => 'কুরিয়ার এন্ট্রি অটোমেশন',
        'customer_delivery_history' => 'কাস্টমার ডেলিভারি হিস্ট্রি',
        'customer_sms_for_order' => 'অর্ডার এসএমএস নোটিফিকেশন',
        'bulk_sms' => 'বাল্ক এসএমএস',
        'ai_text_order_create' => 'টেক্সট থেকে অর্ডার তৈরি',
        'ai_image_to_order_create' => 'ছবি থেকে অর্ডার তৈরি',
        'ai_incomplete_address_autocomplete' => 'অসম্পূর্ণ ঠিকানা অটো-কমপ্লিট',
        'ai_driven_customer_scoring' => 'এআই কাস্টমার স্কোরিং',
        'daily_order_limit' => 'দৈনিক অর্ডার লিমিট',
        'checkout_form_validation' => 'চেকআউট ফর্ম ভ্যালিডেশন',
        'duplicate_order_validation' => 'ডুপ্লিকেট অর্ডার ব্লক',
        'checkout_otp_validation' => 'চেকআউট ওটিপি ভেরিফিকেশন',
        'ip_block' => 'আইপি ব্লক',
        'phone_email_block' => 'ফোন / ইমেইল ব্লক',
        'device_block' => 'ডিভাইস ব্লক',
        'bd_ip_restriction' => 'শুধু বাংলাদেশি আইপি',
        'store_api_checkout_protection' => 'স্টোর API চেকআউট প্রোটেকশন',
        'custom_status_manage' => 'কাস্টম স্ট্যাটাস ম্যানেজ',
        'customer_blacklist' => 'কাস্টমার ব্ল্যাকলিস্ট',
        'marketing_tools' => 'মার্কেটিং টুলস',
        'database_migration' => 'ডাটাবেস মাইগ্রেশন',
        'missing_orders' => 'মিসিং অর্ডার খুঁজুন',
        'missing_order_one_click_create' => 'ওয়ান ক্লিক মিসিং অর্ডার',
        'pos_sticker_print' => 'POS স্টিকার প্রিন্ট',
        'invoice_print' => 'ইনভয়েস প্রিন্ট',
        'order_cloning' => 'অর্ডার ক্লোন',
        'customer_behavior_track' => 'কাস্টমার বিহেভিয়ার ট্র্যাক',
        'repeat_customer_identifier' => 'রিপিট কাস্টমার শনাক্ত',
        'order_source_identifier' => 'অর্ডারে স্টাফ অ্যাসাইন ও সোর্স',
        'inline_shipping_change' => 'ইনলাইন শিপিং পরিবর্তন',
        'order_note_management' => 'অর্ডার নোট ম্যানেজমেন্ট',
        'cod_change' => 'COD পরিবর্তন',
        'ordered_product_management' => 'অর্ডার প্রোডাক্ট ম্যানেজ',
        'order_edit_product_variation' => 'ভ্যারিয়েশন সহ অর্ডার এডিট',
        'quick_action_tool' => 'কুইক অ্যাকশন টুল',
        'courier_auto_status_sync' => 'কুরিয়ার অটো স্ট্যাটাস সিঙ্ক',
        'courier_webhook_integrations' => 'কুরিয়ার ওয়েবহুক',
        'one_click_app_connect' => 'ওয়ান ক্লিক অ্যাপ কানেক্ট',
        'multistore_order_notifications' => 'মাল্টি-স্টোর অর্ডার অ্যালার্ট',
        'customer_call_identifier' => 'কাস্টমার কল শনাক্ত',
        'cross_store_order_detection' => 'ক্রস-স্টোর অর্ডার ডিটেকশন',
        'call_history_with_duration' => 'কল হিস্ট্রি ও ডিউরেশন (অ্যাপ)',
        'common_dashboard' => 'সব ওয়েবসাইটের এক ড্যাশবোর্ড',
        'courier_movement_notification' => 'কুরিয়ার মুভমেন্ট অ্যালার্ট',
        'notification_sound_management' => 'নোটিফিকেশন সাউন্ড কন্ট্রোল',
        'centralized_notifications' => 'সেন্ট্রাল নোটিফিকেশন',
        'admin_employee_manage' => 'স্মার্ট টিম ম্যানেজমেন্ট',
    ],

    'plugin_feature_groups' => [
        'three_courier_partner_integration' => 'Courier',
        'courier_entry_automation' => 'Courier',
        'courier_auto_status_sync' => 'Courier',
        'courier_webhook_integrations' => 'Courier',
        'fraud_customer_checker' => 'Customer',
        'customer_delivery_history' => 'Customer',
        'customer_behavior_track' => 'Customer',
        'repeat_customer_identifier' => 'Customer',
        'customer_sms_for_order' => 'SMS',
        'bulk_sms' => 'SMS',
        'ai_text_order_create' => 'AI Featuree',
        'ai_image_to_order_create' => 'AI Featuree',
        'ai_incomplete_address_autocomplete' => 'AI Featuree',
        'ai_driven_customer_scoring' => 'AI Featuree',
        'checkout_form_validation' => 'Checkout',
        'duplicate_order_validation' => 'Orders',
        'checkout_otp_validation' => 'Checkout',
        'ip_block' => 'Block & restrict',
        'phone_email_block' => 'Block & restrict',
        'device_block' => 'Block & restrict',
        'bd_ip_restriction' => 'Block & restrict',
        'store_api_checkout_protection' => 'Checkout',
        'daily_order_limit' => 'Checkout',
        'custom_status_manage' => 'Orders',
        'customer_blacklist' => 'Block & restrict',
        'database_migration' => 'Tools',
        'marketing_tools' => 'Tools',
        'missing_orders' => 'Orders',
        'missing_order_one_click_create' => 'Orders',
        'pos_sticker_print' => 'Print',
        'invoice_print' => 'Print',
        'order_cloning' => 'Orders',
        'order_source_identifier' => 'Orders',
        'inline_shipping_change' => 'Orders',
        'order_note_management' => 'Orders',
        'cod_change' => 'Orders',
        'ordered_product_management' => 'Orders',
        'order_edit_product_variation' => 'Orders',
        'quick_action_tool' => 'Orders',
    ],

    'feature_descriptions' => [
        'fraud_customer_checker' => 'Order confirm করার আগেই courier data দিয়ে customer check — fake order আটকান।',
        'three_courier_partner_integration' => 'Steadfast, Pathao, RedX — সব কুরিয়ার এক প্ল্যাটফর্ম থেকে ম্যানেজ করুন।',
        'courier_entry_automation' => 'অর্ডার কনফার্ম হলেই অটো কুরিয়ার এন্ট্রি — সময় বাঁচান।',
        'customer_sms_for_order' => 'অর্ডার ও ডেলিভারি আপডেট কাস্টমারকে এসএমএসে পাঠান।',
        'duplicate_order_validation' => 'একই কাস্টমারের ডুপ্লিকেট অর্ডার ব্লক করে লস কমান।',
        'one_click_app_connect' => 'QR স্ক্যানেই ওয়েবসাইট কানেক্ট — সেকেন্ডের মধ্যে প্রস্তুত।',
        'common_dashboard' => '২–৩ বা আনলিমিটেড ওয়েবসাইট এক ড্যাশবোর্ডে — সব আঙুলের ডগায়।',
        'multistore_order_notifications' => 'সব ওয়েবসাইটের নতুন অর্ডার এক অ্যাপে — কখনো মিস করবেন না।',
        'customer_call_identifier' => 'ইনকামিং কলে কাস্টমার শনাক্ত — অর্ডার হিস্ট্রি সহ দ্রুত রেসপন্স।',
        'cross_store_order_detection' => 'এক কাস্টমার অন্য ওয়েবসাইটেও অর্ডার দিয়েছে কিনা শনাক্ত করুন।',
        'call_history_with_duration' => 'কল হিস্ট্রি — অ্যাপ থেকে কল করলে প্রতিটি কলের ডিউরেশন রেকর্ড হয়।',
        'order_source_identifier' => 'অর্ডারে স্টাফ অ্যাসাইন ও সোর্স ট্র্যাক — কে প্রসেস করছে জানুন।',
        'courier_movement_notification' => 'কুরিয়ার মুভমেন্ট অ্যালার্ট সরাসরি ফোনে।',
        'notification_sound_management' => 'স্টোর অনুযায়ী আলাদা নোটিফিকেশন সাউন্ড।',
        'centralized_notifications' => 'সব ওয়েবসাইটের নোটিফিকেশন এক জায়গায় — কোথাও খুঁজতে হবে না।',
        'admin_employee_manage' => 'স্টাফ যোগ, রোল, ওয়েবসাইট অ্যাসাইন ও পোর্টাল — টিম এক জায়গায়।',
        'ai_text_order_create' => 'মেসেজ বা টেক্সট পেস্ট করলেই এআই অর্ডার বানায় — কপি-পেস্ট ঝামেলা নেই।',
        'ai_image_to_order_create' => 'কাস্টমারের স্ক্রিনশট বা ছবি থেকে এআই অর্ডার তৈরি করে।',
        'ai_incomplete_address_autocomplete' => 'অসম্পূর্ণ ঠিকানা এআই দিয়ে অটো পূরণ — ডেলিভারি ফেইল কমে।',
        'ai_driven_customer_scoring' => 'এআই কাস্টমার স্কোরিং — কে বিশ্বস্ত, কে রিস্কি তা দেখুন।',
        'customer_behavior_track' => 'কাস্টমারের আচরণ ট্র্যাক করে স্মার্ট সিদ্ধান্ত নিন।',
        'courier_auto_status_sync' => 'কুরিয়ার স্ট্যাটাস অটো সিঙ্ক — ম্যানুয়াল চেক লাগে না।',
        'invoice_print' => 'ওয়ান ক্লিকে ইনভয়েস ও স্টিকার প্রিন্ট করুন।',
        'missing_orders' => 'FB/মেসেজের অর্ডার WordPress-এ নেই? মিসিং অর্ডার খুঁজে বের করুন।',
        'missing_order_one_click_create' => 'মিসিং অর্ডার ওয়ান ক্লিকে তৈরি — হারানো বিক্রি ফিরিয়ে আনুন।',
        'pos_sticker_print' => 'POS স্টিকার প্রিন্ট — পার্সেল লেবেল সেকেন্ডে, প্যাকিং দ্রুত।',
        'order_cloning' => 'আগের অর্ডার ক্লোন করে দ্রুত নতুন অর্ডার তৈরি করুন।',
        'quick_action_tool' => 'বাল্ক অ্যাকশন — একসাথে অনেক অর্ডার হ্যান্ডেল করুন।',
        'inline_shipping_change' => 'অর্ডারে কুরিয়ার পরিবর্তন — প্যানেলে যেতে হয় না।',
        'order_note_management' => 'অর্ডার নোট ম্যানেজ — টিমের সাথে তথ্য শেয়ার সহজ।',
    ],

    'feature_detail_copy' => [
        'fraud_customer_checker' => [
            'summary' => 'Courier data দিয়ে customer check — order confirm করার আগেই risk দেখুন।',
            'detail' => 'Steadfast, Pathao, RedX-এর delivery history, success rate আর fraud note একসাথে। Landing page-এ free check — registration ছাড়াই।',
        ],
        'duplicate_order_validation' => [
            'summary' => 'Same customer duplicate order block।',
            'detail' => 'Already order দিয়েছে এমন customer আবার order দিলে alert বা block — packaging loss কমে।',
        ],
        'customer_delivery_history' => [
            'summary' => 'Customer-এর আগের delivery record দেখুন।',
            'detail' => 'কতবার order, কত return — এক নজরে। Fraud check-এর সাথে মিলিয়ে decide করুন।',
        ],
        'checkout_otp_validation' => [
            'summary' => 'Checkout-এ OTP — fake order কমে।',
            'detail' => 'Order place করার সময় phone verify — junk order filter।',
        ],
        'admin_employee_manage' => [
            'summary' => 'স্টাফ যোগ, রোল ও ওয়েবসাইট অ্যাসাইন।',
            'detail' => 'প্রতিটি এমপ্লয়ির রোল, কোন ওয়েবসাইটে কাজ করবে, পোর্টাল লগইন — এক জায়গায়। মালিক দেখেন কে কত অর্ডার হ্যান্ডেল করছে।',
        ],
        'call_history_with_duration' => [
            'summary' => 'কল হিস্ট্রি দেখুন — অ্যাপ থেকে কল করলে ডিউরেশন সহ।',
            'detail' => 'প্লাগইন/ড্যাশবোর্ডে কল লগ দেখা যায়। মোবাইল অ্যাপ দিয়ে কল করলে প্রতিটি কল কত মিনিট/সেকেন্ড স্থায়ী হয়েছিল তা সেভ হয় — স্টাফ পারফরম্যান্স ও ক্যানসেল বিশ্লেষণে কাজে লাগে।',
        ],
        'order_source_identifier' => [
            'summary' => 'অর্ডারে স্টাফ অ্যাসাইন — কে প্রসেস করছে জানুন।',
            'detail' => 'প্রতিটি অর্ডারে দায়িত্বশীল স্টাফ সেট করুন। Facebook, হোয়াটসঅ্যাপ বা ওয়েবসাইট — কোথা থেকে অর্ডার এসেছে ও কে হ্যান্ডেল করছে ট্র্যাক হয়। ক্যানসেল হলে কার দায়িত্বে ছিল দেখা যায়।',
        ],
        'customer_call_identifier' => [
            'summary' => 'ইনকামিং কলে কাস্টমার ও অর্ডার শনাক্ত।',
            'detail' => 'কাস্টমার কল করলে অ্যাপ/সিস্টেমে নাম, অর্ডার হিস্ট্রি দেখা যায় — স্টাফ দ্রুত রেসপন্স দিতে পারে, কলের সাথে অর্ডার লিংক হয়।',
        ],
        'three_courier_partner_integration' => [
            'summary' => 'Steadfast, Pathao, RedX এক প্ল্যাটফর্মে।',
            'detail' => 'আলাদা প্যানেলে লগইনের দিন শেষ — সব কুরিয়ার WooEasyLife থেকে।',
        ],
        'courier_entry_automation' => [
            'summary' => 'অর্ডার কনফার্ম = অটো কুরিয়ার এন্ট্রি।',
            'detail' => 'ম্যানুয়াল কপি-পেস্ট বাদ — স্ট্যাটাস বদলালেই কুরিয়ারে যায়।',
        ],
        'courier_auto_status_sync' => [
            'summary' => 'কুরিয়ার স্ট্যাটাস WooCommerce-এ অটো সিঙ্ক।',
            'detail' => 'ডেলিভারি/রিটার্ন আপডেট আলাদা চেক করতে হয় না।',
        ],
        'customer_sms_for_order' => [
            'summary' => 'অর্ডার ও ডেলিভারি আপডেট এসএমএস।',
            'detail' => 'কাস্টমার «পার্সেল কোথায়?» কল কমায় — প্রফেশনাল ইমpression।',
        ],
        'missing_orders' => [
            'summary' => 'WordPress-এ নেই এমন অর্ডার খুঁজুন।',
            'detail' => 'FB/হোয়াটসঅ্যাপে আসা অর্ডার মিস হলে খুঁজে বের করুন।',
        ],
        'missing_order_one_click_create' => [
            'summary' => 'মিসিং অর্ডার ওয়ান ক্লিকে তৈরি।',
            'detail' => 'খুঁজে পাওয়ার পর সেকেন্ডে WooCommerce অর্ডার — হারানো বিক্রি ফিরে।',
        ],
        'order_cloning' => [
            'summary' => 'আগের অর্ডার ক্লোন করে দ্রুত নতুন অর্ডার।',
            'detail' => 'রিপিট কাস্টমার — এক ক্লিকে একই ডিটেইলস।',
        ],
        'quick_action_tool' => [
            'summary' => 'বাল্ক অ্যাকশন — অনেক অর্ডার একসাথে।',
            'detail' => 'স্ট্যাটাস, কুরিয়ার, প্রিন্ট — দ্রুত অপারেশন।',
        ],
        'pos_sticker_print' => [
            'summary' => 'POS স্টিকার — পার্সেল লেবেল প্রিন্ট।',
            'detail' => 'নাম, ঠিকানা, ফোন, COD — স্ট্যান্ডার্ড ফরম্যাটে, ভুল কমে।',
        ],
        'invoice_print' => [
            'summary' => 'ওয়ান ক্লিক ইনভয়েস প্রিন্ট।',
            'detail' => 'প্যাকিং ও রেকর্ডের জন্য প্রস্তুত ইনভয়েস।',
        ],
        'inline_shipping_change' => [
            'summary' => 'অর্ডারে কুরিয়ার পরিবর্তন — প্যানেলে যেতে হয় না।',
            'detail' => 'Steadfast থেকে Pathao — এক ক্লিকে স위চ।',
        ],
        'order_note_management' => [
            'summary' => 'অর্ডার নোট — টিম কমিউনিকেশন।',
            'detail' => 'কাস্টমারের বিশেষ চাহিদা, কলের ফলাফল — সব নোটে।',
        ],
        'ai_text_order_create' => [
            'summary' => 'মেসেজ পেস্ট — এআই অর্ডার বানায়।',
            'detail' => 'হাতে টাইপ ৫–১০ মিনিট → ৩০ সেকেন্ড।',
        ],
        'ai_image_to_order_create' => [
            'summary' => 'ছবি/স্ক্রিনশট থেকে এআই অর্ডার।',
            'detail' => 'কাস্টমার WhatsApp-এ ছবি পাঠাল — এআই parse করে।',
        ],
        'ai_incomplete_address_autocomplete' => [
            'summary' => 'অসম্পূর্ণ ঠিকানা এআই দিয়ে পূরণ।',
            'detail' => '«ঢাকা, গুলশান» — বাকি অংশ সাজেস্ট।',
        ],
        'ai_driven_customer_scoring' => [
            'summary' => 'এআই কাস্টমার রিস্ক স্কোর।',
            'detail' => 'কাকে ফোন-কনফার্ম, কাকে সরাসরি শিপ — ডাটা দিয়ে।',
        ],
        'common_dashboard' => [
            'summary' => 'সব ওয়েবসাইট এক ড্যাশবোর্ডে।',
            'detail' => '২–৩ বা আনলিমিটেড সাইট — এক লগইন, সব অর্ডার।',
        ],
        'multistore_order_notifications' => [
            'summary' => 'সব সাইটের অর্ডার নোটিফিকেশন এক অ্যাপে।',
            'detail' => 'কোন সাইট থেকে অর্ডার — আলাদা খোঁজার দরকার নেই।',
        ],
        'one_click_app_connect' => [
            'summary' => 'QR স্ক্যান — ওয়েবসাইট কানেক্ট।',
            'detail' => 'মিনিটের মধ্যে অ্যাপ + প্লাগইন লাইভ।',
        ],
        'centralized_notifications' => [
            'summary' => 'সেন্ট্রাল নোটিফিকেশন হাব।',
            'detail' => 'অর্ডার, কুরিয়ার, কল — এক জায়গায় অ্যালার্ট।',
        ],
    ],

    'feature_card_colors' => ['violet', 'emerald', 'sky', 'amber', 'rose', 'cyan', 'fuchsia', 'lime'],

    'stats' => [
        ['value' => '৩+', 'label' => 'কুরিয়ার পার্টনার'],
        ['value' => '৪০+', 'label' => 'প্রিমিয়াম ফিচার'],
        ['value' => '২৪/৭', 'label' => 'অর্ডার মনিটরিং'],
        ['value' => '১৪ দিন', 'label' => 'ফ্রি ট্রায়াল'],
    ],

    'loss_comparison' => [
        'headline' => 'Return-এ প্রতিদিন লাখ টাকা loss করছেন?',
        'subtitle' => 'Manual কাজ vs smart automation — আপনি কোন পাশে?',
        'without' => [
            'title' => 'WooEasyLife ছাড়া',
            'items' => [
                'Fake order confirm করে return খরচ',
                'Courier panel-এ manual entry',
                'Duplicate order-এ packaging loss',
                'Site বদলাতে time waste — order miss',
                'Missing FB/WhatsApp order — sale হারানো',
            ],
            'summary' => 'মাসে হাজার হাজার টাকা unnecessary cost',
        ],
        'with' => [
            'title' => 'WooEasyLife দিয়ে',
            'items' => [
                'Order confirm করার আগেই fraud check',
                'অটো কুরিয়ার এন্ট্রি ও স্ট্যাটাস সিঙ্ক',
                'ডুপ্লিকেট ও রিস্কি অর্ডার ব্লক',
                'মোবাইলে রিয়েল-টাইম অর্ডার অ্যালার্ট',
                'একাধিক ওয়েবসাইট এক ড্যাশবোর্ডে',
                'মিসিং অর্ডার রিকভারি ও POS স্টিকার প্রিন্ট',
            ],
            'summary' => 'Fraud কমে profit বাড়ে — confirmed delivery',
        ],
    ],

    'payment_methods' => ['bKash', 'Nagad', 'Rocket', 'Bank'],

    'fraud_check' => [
        'enabled' => env('LANDING_FRAUD_CHECK_ENABLED', true),
        'daily_free_limit' => (int) env('LANDING_FRAUD_CHECK_DAILY_LIMIT', 5),
    ],
];
