<?php

return [
    'whatsapp_phone' => env('LANDING_WHATSAPP_PHONE'),

    'helpline_phone' => env('LANDING_HELPLINE_PHONE', env('LANDING_WHATSAPP_PHONE')),

    'location' => 'ঢাকা, বাংলাদেশ',

    'footer_tagline' => 'বাংলাদেশের WooCommerce মার্চেন্টদের জন্য অল-ইন-ওয়ান অটোমেশন প্ল্যাটফর্ম — আপনার ডাটা, আপনার নিয়ন্ত্রণ।',

    'footer_tagline_en' => "Bangladesh's trusted WooCommerce automation platform. Fraud check, courier sync, AI orders & multi-store management.",

    'trust_badges' => [
        ['icon' => 'check', 'label' => '৪০+ প্রিমিয়াম ফিচার'],
        ['icon' => 'clock', 'label' => '২৪/৭ মনিটরিং'],
        ['icon' => 'lock', 'label' => 'সিকিউর কানেকশন'],
    ],

    'feature_highlight_order' => [
        'ai_text_order_create',
        'ai_image_to_order_create',
        'common_dashboard',
        'multistore_order_notifications',
        'fraud_customer_checker',
        'customer_call_identifier',
        'three_courier_partner_integration',
        'courier_entry_automation',
        'ai_driven_customer_scoring',
        'ai_incomplete_address_autocomplete',
        'cross_store_order_detection',
        'centralized_notifications',
        'duplicate_order_validation',
        'customer_sms_for_order',
        'courier_auto_status_sync',
        'admin_employee_manage',
        'call_history_with_duration',
    ],

    'hero_bullets' => [
        'এআই দিয়ে টেক্সট বা ছবি থেকে সেকেন্ডেই অর্ডার তৈরি',
        'একাধিক ওয়েবসাইট এক ড্যাশবোর্ড ও মোবাইল অ্যাপে — সব আপনার আঙুলের ডগায়',
        'স্মার্ট টিম ম্যানেজমেন্ট — পারফরম্যান্স ট্র্যাক করে দলকে এগিয়ে নিন',
    ],

    'value_pillars' => [
        [
            'id' => 'ai',
            'badge' => 'এআই ইন্টিগ্রেটেড',
            'headline' => 'এআই দিয়ে অর্ডার — হাতে টাইপ করার দিন শেষ',
            'subheadline' => 'কাস্টমারের মেসেজ, ছবি বা অসম্পূর্ণ ঠিকানা থেকে স্মার্ট অর্ডার তৈরি। সময় বাঁচান, ভুল কমান।',
            'accent' => 'fuchsia',
            'feature_keys' => [
                'ai_text_order_create',
                'ai_image_to_order_create',
                'ai_incomplete_address_autocomplete',
                'ai_driven_customer_scoring',
                'customer_behavior_track',
            ],
        ],
        [
            'id' => 'multistore',
            'badge' => 'মাল্টি-স্টোর',
            'headline' => 'একাধিক ওয়েবসাইট — সব আপনার আঙুলের ডগায়',
            'subheadline' => '২–৩টা বা আনলিমিটেড স্টোর এক অ্যাপ ও এক ড্যাশবোর্ডে। সাইট বদলাতে সময় নষ্ট হবে না — সব কিছু হাতের মুঠোয়।',
            'accent' => 'sky',
            'feature_keys' => [
                'common_dashboard',
                'multistore_order_notifications',
                'one_click_app_connect',
                'cross_store_order_detection',
                'centralized_notifications',
                'customer_call_identifier',
            ],
        ],
        [
            'id' => 'team',
            'badge' => 'স্মার্ট টিম ম্যানেজমেন্ট',
            'headline' => 'টিম পারফরম্যান্স ট্র্যাক করুন — সবাই এক লাইনে',
            'subheadline' => 'রোল ভিত্তিক অ্যাক্সেস, স্টোর অনুযায়ী টিম অ্যাসাইন ও কল/অর্ডার পারফরম্যান্স দেখুন। ছোট টিমও বড় ব্যবসার মতো চলবে।',
            'accent' => 'violet',
            'feature_keys' => [
                'admin_employee_manage',
                'call_history_with_duration',
                'customer_call_identifier',
                'order_source_identifier',
            ],
        ],
        [
            'id' => 'protection',
            'badge' => 'ফ্রড প্রোটেকশন',
            'headline' => 'শিপ করার আগেই জানুন — কাস্টমার বিশ্বস্ত কিনা',
            'subheadline' => 'বাংলাদেশের কুরিয়ার ডাটা দিয়ে ফ্রড চেক, ডুপ্লিকেট ব্লক ও চেকআউট সুরক্ষা — রিটার্ন কমান, লাভ বাড়ান।',
            'accent' => 'emerald',
            'feature_keys' => [
                'fraud_customer_checker',
                'duplicate_order_validation',
                'customer_delivery_history',
                'repeat_customer_identifier',
                'checkout_otp_validation',
                'bd_ip_restriction',
            ],
        ],
        [
            'id' => 'automation',
            'badge' => 'ফুল অটোমেশন',
            'headline' => 'কুরিয়ার, এসএমএস, ইনভয়েস — সব অটো',
            'subheadline' => 'Steadfast, Pathao, RedX এক ক্লিকে। অর্ডার কনফার্ম হলেই কুরিয়ার এন্ট্রি, এসএমএস ও স্ট্যাটাস সিঙ্ক।',
            'accent' => 'amber',
            'feature_keys' => [
                'three_courier_partner_integration',
                'courier_entry_automation',
                'courier_auto_status_sync',
                'customer_sms_for_order',
                'invoice_print',
                'missing_order_one_click_create',
            ],
        ],
    ],

    'feature_icons' => [
        'fraud_customer_checker' => 'shield',
        'three_courier_partner_integration' => 'truck',
        'courier_entry_automation' => 'truck',
        'courier_auto_status_sync' => 'truck',
        'courier_webhook_integrations' => 'truck',
        'customer_sms_for_order' => 'message',
        'bulk_sms' => 'message',
        'duplicate_order_validation' => 'clipboard',
        'checkout_form_validation' => 'clipboard',
        'ai_text_order_create' => 'spark',
        'ai_image_to_order_create' => 'spark',
        'invoice_print' => 'print',
        'one_click_app_connect' => 'phone',
        'multistore_order_notifications' => 'phone',
        'customer_call_identifier' => 'phone',
        'common_dashboard' => 'dashboard',
        'admin_employee_manage' => 'users',
        'call_history_with_duration' => 'phone',
        'order_source_identifier' => 'clipboard',
    ],

    'groups' => [
        'Courier' => 'কুরিয়ার অটোমেশন',
        'Customer' => 'কাস্টমার ইন্টেলিজেন্স',
        'SMS' => 'এসএমএস নোটিফিকেশন',
        'AI Featuree' => 'এআই ফিচার',
        'Checkout' => 'চেকআউট সুরক্ষা',
        'Orders' => 'অর্ডার ম্যানেজমেন্ট',
        'Block & restrict' => 'ফ্রড ও ব্লক',
        'Tools' => 'বিজনেস টুলস',
        'Print' => 'প্রিন্ট ও ইনভয়েস',
        'App' => 'মোবাইল অ্যাপ',
    ],

    'labels' => [
        'fraud_customer_checker' => 'ফ্রড কাস্টমার চেকার',
        'three_courier_partner_integration' => '৩টি কুরিয়ার পার্টনার ইন্টিগ্রেশন',
        'courier_entry_automation' => 'কুরিয়ার এন্ট্রি অটোমেশন',
        'customer_delivery_history' => 'কাস্টমার ডেলিভারি হিস্ট্রি',
        'customer_sms_for_order' => 'অর্ডার এসএমএস নোটিফিকেশন',
        'bulk_sms' => 'বাল্ক এসএমএস',
        'ai_text_order_create' => 'টেক্সট থেকে অর্ডার তৈরি',
        'ai_image_to_order_create' => 'ছবি থেকে অর্ডার তৈরি',
        'ai_incomplete_address_autocomplete' => 'অসম্পূর্ণ ঠিকানা অটো-কমপ্লিট',
        'ai_driven_customer_scoring' => 'এআই কাস্টমার স্কোরিং',
        'daily_order_limit' => 'দৈনিক অর্ডার লিমিট',
        'checkout_form_validation' => 'চেকআউট ফর্ম ভ্যালিডেশন',
        'duplicate_order_validation' => 'ডুপ্লিকেট অর্ডার ব্লক',
        'checkout_otp_validation' => 'চেকআউট ওটিপি ভেরিফিকেশন',
        'ip_block' => 'আইপি ব্লক',
        'phone_email_block' => 'ফোন / ইমেইল ব্লক',
        'device_block' => 'ডিভাইস ব্লক',
        'bd_ip_restriction' => 'শুধু বাংলাদেশি আইপি',
        'store_api_checkout_protection' => 'স্টোর API চেকআউট প্রোটেকশন',
        'custom_status_manage' => 'কাস্টম স্ট্যাটাস ম্যানেজ',
        'customer_blacklist' => 'কাস্টমার ব্ল্যাকলিস্ট',
        'marketing_tools' => 'মার্কেটিং টুলস',
        'database_migration' => 'ডাটাবেস মাইগ্রেশন',
        'missing_orders' => 'মিসিং অর্ডার খুঁজুন',
        'missing_order_one_click_create' => 'ওয়ান ক্লিক মিসিং অর্ডার',
        'pos_sticker_print' => 'POS স্টিকার প্রিন্ট',
        'invoice_print' => 'ইনভয়েস প্রিন্ট',
        'order_cloning' => 'অর্ডার ক্লোন',
        'customer_behavior_track' => 'কাস্টমার বিহেভিয়ার ট্র্যাক',
        'repeat_customer_identifier' => 'রিপিট কাস্টমার শনাক্ত',
        'order_source_identifier' => 'অর্ডার সোর্স শনাক্ত',
        'inline_shipping_change' => 'ইনলাইন শিপিং পরিবর্তন',
        'order_note_management' => 'অর্ডার নোট ম্যানেজমেন্ট',
        'cod_change' => 'COD পরিবর্তন',
        'ordered_product_management' => 'অর্ডার প্রোডাক্ট ম্যানেজ',
        'order_edit_product_variation' => 'ভ্যারিয়েশন সহ অর্ডার এডিট',
        'quick_action_tool' => 'কুইক অ্যাকশন টুল',
        'courier_auto_status_sync' => 'কুরিয়ার অটো স্ট্যাটাস সিঙ্ক',
        'courier_webhook_integrations' => 'কুরিয়ার ওয়েবহুক',
        'one_click_app_connect' => 'ওয়ান ক্লিক অ্যাপ কানেক্ট',
        'multistore_order_notifications' => 'মাল্টি-স্টোর অর্ডার অ্যালার্ট',
        'customer_call_identifier' => 'কাস্টমার কল শনাক্ত',
        'cross_store_order_detection' => 'ক্রস-স্টোর অর্ডার ডিটেকশন',
        'call_history_with_duration' => 'কল পারফরম্যান্স ট্র্যাকিং',
        'common_dashboard' => 'সব স্টোরের এক ড্যাশবোর্ড',
        'courier_movement_notification' => 'কুরিয়ার মুভমেন্ট অ্যালার্ট',
        'notification_sound_management' => 'নোটিফিকেশন সাউন্ড কন্ট্রোল',
        'centralized_notifications' => 'সেন্ট্রাল নোটিফিকেশন',
        'admin_employee_manage' => 'স্মার্ট টিম ম্যানেজমেন্ট',
    ],

    'plugin_feature_groups' => [
        'three_courier_partner_integration' => 'Courier',
        'courier_entry_automation' => 'Courier',
        'courier_auto_status_sync' => 'Courier',
        'courier_webhook_integrations' => 'Courier',
        'fraud_customer_checker' => 'Customer',
        'customer_delivery_history' => 'Customer',
        'customer_behavior_track' => 'Customer',
        'repeat_customer_identifier' => 'Customer',
        'customer_sms_for_order' => 'SMS',
        'bulk_sms' => 'SMS',
        'ai_text_order_create' => 'AI Featuree',
        'ai_image_to_order_create' => 'AI Featuree',
        'ai_incomplete_address_autocomplete' => 'AI Featuree',
        'ai_driven_customer_scoring' => 'AI Featuree',
        'checkout_form_validation' => 'Checkout',
        'duplicate_order_validation' => 'Orders',
        'checkout_otp_validation' => 'Checkout',
        'ip_block' => 'Block & restrict',
        'phone_email_block' => 'Block & restrict',
        'device_block' => 'Block & restrict',
        'bd_ip_restriction' => 'Block & restrict',
        'store_api_checkout_protection' => 'Checkout',
        'daily_order_limit' => 'Checkout',
        'custom_status_manage' => 'Orders',
        'customer_blacklist' => 'Block & restrict',
        'database_migration' => 'Tools',
        'marketing_tools' => 'Tools',
        'missing_orders' => 'Orders',
        'missing_order_one_click_create' => 'Orders',
        'pos_sticker_print' => 'Print',
        'invoice_print' => 'Print',
        'order_cloning' => 'Orders',
        'order_source_identifier' => 'Orders',
        'inline_shipping_change' => 'Orders',
        'order_note_management' => 'Orders',
        'cod_change' => 'Orders',
        'ordered_product_management' => 'Orders',
        'order_edit_product_variation' => 'Orders',
        'quick_action_tool' => 'Orders',
    ],

    'feature_descriptions' => [
        'fraud_customer_checker' => 'শিপ করার আগেই কুরিয়ার ডাটা দিয়ে কাস্টমার যাচাই — ফেইক অর্ডার আটকান।',
        'three_courier_partner_integration' => 'Steadfast, Pathao, RedX — সব কুরিয়ার এক প্ল্যাটফর্ম থেকে ম্যানেজ করুন।',
        'courier_entry_automation' => 'অর্ডার কনফার্ম হলেই অটো কুরিয়ার এন্ট্রি — সময় বাঁচান।',
        'customer_sms_for_order' => 'অর্ডার ও ডেলিভারি আপডেট কাস্টমারকে এসএমএসে পাঠান।',
        'duplicate_order_validation' => 'একই কাস্টমারের ডুপ্লিকেট অর্ডার ব্লক করে লস কমান।',
        'multistore_order_notifications' => 'সব স্টোরের নতুন অর্ডার এক অ্যাপে — কখনো মিস করবেন না।',
        'customer_call_identifier' => 'ইনকামিং কলে কাস্টমার শনাক্ত — স্টাফ দ্রুত রেসপন্স দিতে পারে।',
        'cross_store_order_detection' => 'এক কাস্টমার অন্য স্টোরেও অর্ডার দিয়েছে কিনা শনাক্ত করুন।',
        'call_history_with_duration' => 'কোন স্টাফ কতক্ষণ কল করল — পারফরম্যান্স মাপুন ও টিম উন্নত করুন।',
        'order_source_identifier' => 'কোন এমপ্লয়ি কোন অর্ডার হ্যান্ডেল করছে তা শনাক্ত করুন।',
        'courier_movement_notification' => 'কুরিয়ার মুভমেন্ট অ্যালার্ট সরাসরি ফোনে।',
        'notification_sound_management' => 'স্টোর অনুযায়ী আলাদা নোটিফিকেশন সাউন্ড।',
        'centralized_notifications' => 'সব স্টোরের নোটিফিকেশন এক জায়গায় — কোথাও খুঁজতে হবে না।',
        'admin_employee_manage' => 'রোল, স্টোর অ্যাসাইন ও পোর্টাল অ্যাক্সেস — টিম এক জায়গায় ম্যানেজ করুন।',
        'ai_text_order_create' => 'মেসেজ বা টেক্সট পেস্ট করলেই এআই অর্ডার বানায় — কপি-পেস্ট ঝামেলা নেই।',
        'ai_image_to_order_create' => 'কাস্টমারের স্ক্রিনশট বা ছবি থেকে এআই অর্ডার তৈরি করে।',
        'ai_incomplete_address_autocomplete' => 'অসম্পূর্ণ ঠিকানা এআই দিয়ে অটো পূরণ — ডেলিভারি ফেইল কমে।',
        'ai_driven_customer_scoring' => 'এআই কাস্টমার স্কোরিং — কে বিশ্বস্ত, কে রিস্কি তা দেখুন।',
        'customer_behavior_track' => 'কাস্টমারের আচরণ ট্র্যাক করে স্মার্ট সিদ্ধান্ত নিন।',
        'courier_auto_status_sync' => 'কুরিয়ার স্ট্যাটাস অটো সিঙ্ক — ম্যানুয়াল চেক লাগে না।',
        'invoice_print' => 'ওয়ান ক্লিকে ইনভয়েস ও স্টিকার প্রিন্ট করুন।',
        'one_click_app_connect' => 'QR স্ক্যানেই স্টোর কানেক্ট — সেকেন্ডের মধ্যে প্রস্তুত।',
        'common_dashboard' => '২–৩ বা আনলিমিটেড স্টোর এক ড্যাশবোর্ডে — সব আঙুলের ডগায়।',
    ],

    'feature_card_colors' => ['violet', 'emerald', 'sky', 'amber', 'rose', 'cyan', 'fuchsia', 'lime'],

    'stats' => [
        ['value' => '৩+', 'label' => 'কুরিয়ার পার্টনার'],
        ['value' => '৪০+', 'label' => 'প্রিমিয়াম ফিচার'],
        ['value' => '২৪/৭', 'label' => 'অর্ডার মনিটরিং'],
        ['value' => '১৪ দিন', 'label' => 'ফ্রি ট্রায়াল'],
    ],

    'loss_comparison' => [
        'headline' => 'রিটার্নে প্রতিদিন লাখ টাকা লস করছেন?',
        'subtitle' => 'ম্যানুয়াল কাজ vs স্মার্ট অটোমেশন — আপনি কোন পাশে?',
        'without' => [
            'title' => 'WooEasyLife ছাড়া',
            'items' => [
                'ফেইক অর্ডার শিপ করে রিটার্ন খরচ',
                'কুরিয়ার প্যানেলে ম্যানুয়াল এন্ট্রি',
                'ডুপ্লিকেট অর্ডারে প্যাকেজিং লস',
                'সাইট বদলাতে সময় নষ্ট — অর্ডার মিস',
            ],
            'summary' => 'মাসে হাজার হাজার টাকা অযথা খরচ',
        ],
        'with' => [
            'title' => 'WooEasyLife দিয়ে',
            'items' => [
                'শিপ করার আগেই ফ্রড চেক',
                'অটো কুরিয়ার এন্ট্রি ও স্ট্যাটাস সিঙ্ক',
                'ডুপ্লিকেট ও রিস্কি অর্ডার ব্লক',
                'মোবাইলে রিয়েল-টাইম অর্ডার অ্যালার্ট',
                'একাধিক স্টোর এক ড্যাশবোর্ডে — সব আঙুলের ডগায়',
            ],
            'summary' => 'ফ্রড কমে লাভ বাড়ে — নিশ্চিত ডেলিভারি',
        ],
    ],

    'payment_methods' => ['bKash', 'Nagad', 'Rocket', 'Bank'],

    'fraud_check' => [
        'enabled' => env('LANDING_FRAUD_CHECK_ENABLED', true),
        'daily_free_limit' => (int) env('LANDING_FRAUD_CHECK_DAILY_LIMIT', 5),
    ],
];
