<?php

return [
    'durations' => [
        'free_trial',
        '1_month',
        '5_month',
        '1_year',
    ],

    'plugin_feature_keys' => [
        'fraud_customer_checker',
        'three_courier_partner_integration',
        'courier_entry_automation',
        'customer_delivery_history',
        'customer_sms_for_order',
        'bulk_sms',
        'ai_text_order_create',
        'ai_image_to_order_create',
        'ai_incomplete_address_autocomplete',
        'ai_driven_customer_scoring',
        'daily_order_limit',
        'checkout_form_validation',
        'duplicate_order_validation',
        'checkout_otp_validation',
        'ip_block',
        'phone_email_block',
        'device_block',
        'bd_ip_restriction',
        'store_api_checkout_protection',
        'custom_status_manage',
        'customer_blacklist',
        'marketing_tools',
        'database_migration',
        'missing_orders',
        'missing_order_one_click_create',
        'pos_sticker_print',
        'invoice_print',
        'order_cloning',
        'customer_behavior_track',
        'repeat_customer_identifier',
        'order_source_identifier',
        'inline_shipping_change',
        'order_note_management',
        'cod_change',
        'ordered_product_management',
        'order_edit_product_variation',
        'quick_action_tool',
        'courier_auto_status_sync',
        'courier_webhook_integrations',
    ],

    'app_feature_keys' => [
        'one_click_app_connect',
        'multistore_order_notifications',
        'customer_call_identifier',
        'cross_store_order_detection',
        'call_history_with_duration',
        'common_dashboard',
        'courier_movement_notification',
        'notification_sound_management',
        'centralized_notifications',
        'admin_employee_manage',
    ],
];
