name: Publish Website to CPanel
on:
  push:
    branches:
      - SEO-Optimizations

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, bcmath

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📦 Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.APP_FTP_SERVER }}
          port: 21
          username: ${{ secrets.APP_FTP_USERNAME }}
          password: ${{ secrets.APP_FTP_PASSWORD }}
